services:
  postgres-server:
    image: postgres
    restart: no
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-simple_invoice}
      POSTGRES_USER: ${DB_USER:-db}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-db} -d ${DB_NAME:-simple_invoice}" ]
      interval: 1s
      timeout: 5s
      retries: 5

  s3-server:
    image: minio/minio
    restart: no
    ports:
      - ${S3_PORT:-9000}:9000
      - ${S3_ADM_PORT:-9001}:9001
    volumes:
      - s3-data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-doc}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    command: server /data --console-address ":${S3_ADM_PORT:-9001}"
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: .
    image: ghcr.io/tor-jorgen/simpleinvoice-server:1.2.2
    restart: no
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-ERROR}
      SIMPLE_INVOICE_LOG_LEVEL: ${SIMPLE_INVOICE_LOG_LEVEL:-ERROR}
      SERVER_PORT: ${SERVER_PORT:-8080}
      DB_CONNECTION_PRE: ${DB_CONNECTION_PRE:-jdbc:postgresql://postgres-server}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-simple_invoice}
      DB_USER: ${DB_USER:-db}
      DB_PASSWORD: ${DB_PASSWORD}
      S3_CONNECTION_PRE: ${S3_CONNECTION_PRE:-http://s3-server}
      S3_PORT: ${S3_PORT:-9000}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-doc}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      FLYWAY_LOCATIONS: filesystem:/migrations
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-xxx}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-yyy}
      ALLOW_HOSTS: ${ALLOW_HOSTS:-http://localhost:8000}
      SMTP_USER_NAME: ${SMTP_USER_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
    depends_on:
      postgres-server:
        condition: service_healthy
      s3-server:
        condition: service_healthy

  app:
    build:
      context: ${APP_BUILD_CONTEXT:-../simpleinvoice-app}
      dockerfile: ${APP_BUILD_DOCKERFILE:-Dockerfile}
      args:
        API_BASE_URL: ${API_BASE_URL:-http://localhost:8080}
    image: ghcr.io/tor-jorgen/simpleinvoice-app:1.1.1
    restart: no
    ports:
      - ${APP_PORT:-8000}:${APP_PORT:-8000}
    depends_on:
      - server

volumes:
  db-data:
    name: simple-invoice-db-data
  s3-data:
    name: simple-invoice-s3-data
