services:
  postgres:
    image: postgres
    restart: no
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ${DB_DATA_PATH:-./.postgres}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-simple_invoice}
      POSTGRES_USER: ${DB_USER:-db}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-db} -d ${DB_NAME:-simple_invoice}" ]
      interval: 1s
      timeout: 5s
      retries: 5

  server:
    build: .
    image: simpleinvoice-server
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    volumes:
      - ${CFG_PATH:-./.config}:/config
      - ${DOCUMENT_PATH:-./.documents}:/documents
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      DB_CONNECTION_PRE: ${DB_CONNECTION_PRE:-jdbc:postgresql://host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-simple_invoice}
      DB_USER: ${DB_USER:-db}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CSRF_TOKEN: ${CSRF_TOKEN}
      SMTP_USER_NAME: ${SMTP_USER_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
    depends_on:
      postgres:
        condition: service_healthy
