services:
  postgres-server:
    image: postgres
    restart: no
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-simple_invoice}
      POSTGRES_USER: ${DB_USER:-db}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-db} -d ${DB_NAME:-simple_invoice}" ]
      interval: 1s
      timeout: 5s
      retries: 5

  server:
    build: .
    image: simpleinvoice-server
    restart: no
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    volumes:
      - ${CFG_PATH:-./.config}:/config
      - documents:/documents
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      DB_CONNECTION_PRE: ${DB_CONNECTION_PRE:-jdbc:postgresql://postgres-server}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-simple_invoice}
      DB_USER: ${DB_USER:-db}
      DB_PASSWORD: ${DB_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/migrations
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      ALLOW_HOSTS: ${ALLOW_HOSTS:-http://localhost:8000}
      CSRF_TOKEN: ${CSRF_TOKEN}
      SMTP_USER_NAME: ${SMTP_USER_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
    depends_on:
      postgres-server:
        condition: service_healthy

  app:
    build:
      context: ${APP_BUILD_CONTEXT:-../simpleinvoice-app}
      dockerfile: ${APP_BUILD_DOCKERFILE:-Dockerfile}
      args:
        API_BASE_URL: ${API_BASE_URL:-http://localhost:8080}
        CSRF_TOKEN: ${CSRF_TOKEN}
    image: simpleinvoice-app
    restart: no
    ports:
      - ${APP_PORT:-8000}:${APP_PORT:-8000}
    depends_on:
      postgres-server:
        condition: service_healthy

volumes:
  db-data:
    name: simple-invoice-db-data
  documents:
    name: simple-invoice-documents
