services:
  postgres:
    image: postgres
    restart: no
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: simple_invoice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hugo
      POSTGRES_HOST_AUTH_METHOD: trust
