ktor:
  application:
    modules:
      - org.simpleinvoice.server.ApplicationKt.module
  deployment:
    port: "$SERVER_PORT:8080"

db:
  connectionPrefix: "$DB_CONNECTION_PRE:jdbc:postgresql://localhost"
  port: "$DB_PORT:5432"
  name: "$DB_NAME:simple_invoice"
  user: "$DB_USER:db"
  password: "$DB_PASSWORD"

security:
  clientId: "$GOOGLE_CLIENT_ID"
  clientSecret: "$GOOGLE_CLIENT_SECRET"

smtp:
  host: "$SMTP_HOST:smtp.gmail.com"
  port: "$SMTP_PORT:587"
  tls: "$SMTP_TLS:true"
  username: "$SMTP_USER_NAME"
  password: "$SMTP_PASSWORD"
  senderEmail: "$SMTP_SENDER_EMAIL"
  senderName: "$SMTP_SENDER_NAME"

invoice:
  invoiceDirectory: "$INVOICE_INVOICE_DIRECTORY:./.documents"
  template: "$INVOICE_INVOICE_TEMPLATE:./.config/invoice.odt"
  invoiceName: "$INVOICE_INVOICE_NAME:_NO_-_HOUSEHOLD_"
