ktor:
  application:
    modules:
      - org.simpleinvoice.server.ApplicationKt.module
  deployment:
    port: "$SERVER_PORT:8080"

db:
  connectionPrefix: "$DB_CONNECTION_PRE:jdbc:postgresql://localhost"
  port: "$DB_PORT:5432"
  name: "$DB_NAME:simple_invoice"
  user: "$DB_USER:db"
  password: "$DB_PASSWORD"

s3:
  connectionPrefix: "$S3_CONNECTION_PRE:http://localhost"
  port: "$S3_PORT:9000"
  accessKeyId: "$S3_ACCESS_KEY_ID:doc"
  secretAccessKey: "$S3_SECRET_ACCESS_KEY"

security:
  clientId: "$GOOGLE_CLIENT_ID:xxx"
  clientSecret: "$GOOGLE_CLIENT_SECRET:yyy"
  allowHosts: "$ALLOW_HOSTS:http://localhost:8000"

smtp:
  host: "$SMTP_HOST:smtp.gmail.com"
  port: "$SMTP_PORT:587"
  tls: "$SMTP_TLS:true"
  username: "$SMTP_USER_NAME"
  password: "$SMTP_PASSWORD"
  senderEmail: "$SMTP_SENDER_EMAIL"
  senderName: "$SMTP_SENDER_NAME"

invoice:
  configBucketName: "$INVOICE_CONFIG_BUCKET_NAME:simple-invoice-config"
  invoiceBucketName: "$INVOICE_BUCKET_NAME:simple-invoice-invoices"
  invoiceTemplateName: "$INVOICE_TEMPLATE_NAME:invoice.odt"
  invoiceName: "$INVOICE_NAME:_NO_-_HOUSEHOLD_"
