ktor:
  application:
    modules:
      - org.simpleinvoice.server.ApplicationKt.module
  deployment:
    port: "$SERVER_PORT:8080"

db:
  connectionPrefix: "$DB_CONNECTION_PRE:jdbc:postgresql://localhost"
  port: "$DB_PORT:5432"
  name: "$DB_NAME:simple_invoice"
  user: "$DB_USER"
  password: "$DB_PASSWORD"

cfg:
  invoice: "$INVOICE_CONFIG:./config/config.yml"
  batch: "$BATCH_CONFIG:./config/batch.yml"

security:
  clientId: "$GOOGLE_CLIENT_ID"
  clientSecret: "$GOOGLE_CLIENT_SECRET"

smtp:
  host: smtp.gmail.com
  port: 587
  tls: true