name: Build pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ github.repository }}
  DISTRIBUTION: temurin
  JAVA_VERSION: 24

jobs:
  lint-code:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Lint code with Super-Linter
        uses: super-linter/super-linter@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_YAML: true

  lint-workflow:
    name: Lint Workflow YAML
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          github_token: ${{ secrets.GITHUB_TOKEN }}

  gradle-build-and-test:
    name: Gradle Build and Test
    runs-on: ubuntu-latest
    needs: [ lint-code, lint-workflow ]
    outputs:
      build-artifact-name: gradle-reports
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      - name: Run Gradle check
        run: ./gradlew check -x test
      # Archive the build directory (reports, classes, etc.)
      - name: Upload Gradle build artifacts
        id: upload-reports
        uses: actions/upload-artifact@v5
        with:
          name: gradle-reports
          path: build/

  sonar-analysis:
    name: SonarCloud Analysis
    needs: [ gradle-build-and-test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      # The artifact name is hardcoded (or could be retrieved from needs.gradle-build-and-test.outputs.build-artifact-name)
      - name: Download Gradle build artifacts
        uses: actions/download-artifact@v6
        with:
#          name: gradle-reports
          name: ${{ needs.gradle-build-and-test.outputs.build-artifact-name }}
          path: build/
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      # Run Sonar analysis, skipping the build step to reuse existing reports
      - name: Run SonarCloud analysis
        run: ./gradlew sonar -x compileJava -x test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish-and-scan-image:
    name: Publish and san image
    needs: [ sonar-analysis, gradle-build-and-test ]
    runs-on: ubuntu-latest
    if: success()
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Download Gradle build artifacts
        uses: actions/download-artifact@v6
        with:
          name: gradle-reports
          path: build/
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
      - name: Scan image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL
          vuln-type: os,library
          exit-code: 1
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
